name: "Network-Config-Test"
x-type: "hlfv1"
description: "The network used in the integration tests"
version: 1.0.0

client:
  organization: OrgB
  credentialStore:
    path: "/tmp/hfc-kvs"
    cryptoStore:
      path: "/tmp/hfc-cvs"
    wallet: wallet-name

channels:
  txchannel:
    orderers:
      - Orderer0
    peers:
      peer0:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - bimcc:v1.04

organizations:
  OrgB:
    mspid: OrgB
    peers:
      - peer0

    adminPrivateKey:
        path: E:\crypto-config\peerOrganizations\orgb.example.com\users\Admin@orgb.example.com\msp\keystore\8f62dc9246ad04465ae36bafa78267828ef1688bf84ce9c19c69c4a36e60080a_sk

    signedCert:
      path: E:\crypto-config\peerOrganizations\orgb.example.com\users\Admin@orgb.example.com\msp\signcerts\Admin@orgb.example.com-cert.pem

orderers:
  Orderer0:
    url: grpcs://orderer0.example.com:7050
    tlsCACerts:
      path: E:\crypto-config\ordererOrganizations\example.com\tlsca\tlsca.example.com-cert.pem
    grpcOptions:
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000

peers:
  peer0:
    url: grpcs://peer0.orgb.example.com:7051
    tlsCACerts:
      path: E:\crypto-config\peerOrganizations\orgb.example.com\tlsca\tlsca.orgb.example.com-cert.pem
    grpcOptions:
      grpc.http2.keepalive_time: 15

